services:
  attacker:
    container_name: assignment_4_syn_flood_attacker
    hostname: attacker
    build:
      context: .
      dockerfile: host.Dockerfile
    command: tail -F anything
    networks:
      lab_net_1:
        ipv4_address: 192.168.124.10
    working_dir: /solution
    volumes:
      - type: bind
        source: ./solution
        target: /solution

  client:
    container_name: assignment_4_syn_flood_client
    hostname: client
    build:
      context: .
      dockerfile: host.Dockerfile
    command: tail -F anything
    networks:
      lab_net_1:
        ipv4_address: 192.168.124.11

  blackhole_gateway:
    container_name: assignment_4_syn_flood_blackhole_gateway
    hostname: webserver
    image: debian:bookworm
    command: tail -F anything
    sysctls:
      - net.ipv4.ip_forward=0
    networks:
      lab_net_1:
        ipv4_address: 192.168.124.2

  webserver:
    container_name: assignment_4_syn_flood_webserver
    hostname: webserver
    cap_add:
      - NET_ADMIN
    build:
      context: ./webserver
    command: sh -c "ip route replace default via 192.168.124.2 && /entrypoint.sh"
    sysctls:
      - net.ipv4.tcp_syncookies=0
      - net.ipv4.tcp_max_syn_backlog=5
      - net.core.somaxconn=5
      - net.ipv4.tcp_synack_retries=1
    networks:
      lab_net_1:
        ipv4_address: 192.168.124.20

networks:
  lab_net_1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.124.0/24
    driver_opts:
      com.docker.network.bridge.name: assignment_4
